#!/bin/bash


function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo "$REASON"
    fi

    echo ""

    exit 1
}


if ! [ "$TERMUX_VERSION" == "" ] && [ "$ANDROID_DATA" == "" ];
then
    abort "This script is for Termux proots only."
fi




SSHD_PID=$(cat /var/run/sshd.pid)

if ! [ "$SSHD_PID" == "" ];
then
    if [ -f "/proc/${SSHD_PID}/cmdline" ];
    then
        cat "/proc/${SSHD_PID}/cmdline" | grep -q "/usr/sbin/sshd"

        if [ "$?" == "0" ];
        then
            kill -9 $SSHD_PID
            
            exit 0
        fi
    fi
fi

exit 1