#!/bin/bash

function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""

    exit 1
}


SCRIPT_PATH=$(realpath $(dirname $0))




PROOT_TOOLS_PATH=$SCRIPT_PATH/proot


echo "Preparing to setup x86 proot (with Box86) ..."
echo ""

export PROOT_DISTRO="debian-oldstable"
export PROOT_NAME="box86"


ARCH=$(uname -m)

if [ "$ARCH" == "i386" ];
then
    export DISTRO_ARCH="arm"

    echo "Detected i386 architecture. Installing an ARM proot."
    echo "Installing needed packages ... "
    echo "===================================================="

    pkg install -y qemu-user-arm qemu-user-i386

    if [ "$?" == "1" ];
    then
        abort "Failed!"
    fi

elif [ "$ARCH" == "x86_64" ];
then
    export DISTRO_ARCH="aarch64"

    echo "Detected AMD64 architecture. Installing an ARM64 proot."
    echo "Installing needed packages ..."
    echo "======================================================="

    pkg install -y qemu-user-arm qemu-user-i386 \
                   qemu-user-aarch64 qemu-user-x86-64

    if [ "$?" == "1" ];
    then
        abort "Failed!"
    fi
fi


"$PROOT_TOOLS_PATH/setup" 


if [ "$?" == "0" ];
then
    "$PROOT_TOOLS_PATH/scripts/pexec_admin" $PROOT_NAME \
        "apt update"

    "$PROOT_TOOLS_PATH/scripts/pexec_admin" $PROOT_NAME \
        "apt upgrade -y"

    "$PROOT_TOOLS_PATH/scripts/pexec_admin" $PROOT_NAME \
        "apt install -y dialog gpg git sudo wget"

    if ! [ "$?" == "0" ];
    then
        abort "${PROOT_DISTRO} setup: Some packages failed to install."
    fi


    "$PROOT_TOOLS_PATH/scripts/pexec_admin" $PROOT_NAME \
        "git clone https://github.com/arithesage/box86-setup.git --depth 1"

    if ! [ "$?" == "0" ];
    then
        abort "Couldn't download box86-setup in ${PROOT_DISTRO} proot."
    fi


    "$PROOT_TOOLS_PATH/scripts/pexec_admin" $PROOT_NAME \
        "\$HOME/box86-setup/installer"

    if ! [ "$?" == "0" ];
    then
        abort "Box86 installation failed."
    fi


    echo "All done."
    echo ""
fi










