#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}


if [ "$TERMUX_VERSION" == "" ];
then
    abort "This script is only for Termux."
fi


echo ""
echo "Searching for external SD card..."


if ! [ -d "$HOME/storage" ];
then
    echo ""
    echo "Can't access Android filesystem."
    echo "Execute 'termux-setup-storage' first, to grant Termux permission."
    echo ""
    echo "It is also recommended, if you have not done it yet,"
    echo "to execute 'termux-change-repo' for selecting a mirror"
    echo "for downloading the packages, although is not strictly necesary."
    echo ""

    abort
fi


if ! [ -d "$HOME/storage/external-1" ];
then
    echo ""
    echo "No external SD card detected."
    echo "Skipping setting up extsd_id."
    echo ""

else
    if ! [ -f "$HOME/.extsd_id" ];
    then
        extsd_path=$(realpath "$HOME/storage/external-1")
        extsd_id=${extsd_path:9:9}

        echo $extsd_id > "$HOME/.extsd_id"

        if ! [ -f "$HOME/.environment" ];
        then
            echo "export EXT_SD=\"/storage/${extsd_id}\"" >> "$HOME/.environment"
        fi

        echo ""
        echo "Added ~/.extsd_id file with the SD card ID."
        echo "Also, an EXT_SD variable has been added to .environment with its"
        echo "full path (more confortable that writing '/storage/external-1')."
        echo ""
        echo "Remember: New environment variables will be set after restarting"
        echo "          Termux."
        echo ""
    fi
fi