#!/bin/bash


function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}




SCRIPT_DIR=$(realpath $(dirname $0))

if ! [ -f "$PREFIX/bin/termux-x11" ];
then
    abort "VirGL requires installing termux-x11 before."
fi


if [ -f "$PREFIX/lib/libvirglrenderer.so" ];
then
    abort "VirGL seems already installed."
fi


echo "Setting up VirGL..."
echo "==================="

if ! [ -f $PREFIX/etc/apt/sources.list.d/tur.list ];
then
    echo ""
    echo "Installing 'tur' repository ..."
    echo "==============================="    

    pkg update
    pkg install -y tur-repo

    if ! [ "$?" == "0" ];
    then
        abort "Failed!"
    fi    
fi


echo ""
echo "Installing mesa, virgl and vulkan packages ..."
echo "=============================================="

pkg install -y mesa-zink virglrenderer-mesa-zink vulkan-loader-android

if ! [ "$?" == "0" ];
then
    abort "Failed!"
fi


if ! [ -f "$HOME/.virgl_environment" ];
then
    cp "$SCRIPT_DIR/.virgl_environment" "$HOME/"
    echo "source \$HOME/.virgl_environment" >> $HOME/.bashrc
fi


