#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}


function usage
{
    echo ""
}


if [ "$1" == "-h" ] || [ "$1" == "--h" ];
then
    usage
    abort
fi




TERMUX_SETUP_REPO="https://github.com/arithesage/termux-setup.git"


echo "=================================="
echo "Performing a basic Termux setup..."
echo "=================================="

if ! [ -f "$HOME/.bashrc" ];
then
    cp "$PREFIX/etc/bash.bashrc" "$HOME/.bashrc"
fi

if ! [ -f "$HOME/.environment" ];
then
    touch "$HOME/.environment"
    echo "source \$HOME/.environment" >> "$HOME/.bashrc"
fi


echo "Checking available packages..."
echo "------------------------------"

pkg update

echo ""


NEEDED_PACKAGES=""


if ! [ -f "$PREFIX/bin/git" ];
then
    NEEDED_PACKAGES+="git "
fi


if ! [ -f "$PREFIX/bin/sshd" ];
then
    NEEDED_PACKAGES+="openssh "
fi


if ! [ "$NEEDED_PACKAGES" == "" ];
then
    echo "Installing some needed packages..."
    echo "----------------------------------"

    pkg install -y $NEEDED_PACKAGES
fi

echo ""


echo "$NEEDED_PACKAGES" | grep openssh

if [ "$?" == "0" ];
then
    echo "sshd" >> "$HOME/.bashrc"
    
    echo "Added sshd to startup."
    echo "Please, enter a password for login."
    echo ""

    passwd
fi


echo ""
echo "Cloning 'termux-setup' repository..."
echo "------------------------------------"

git clone $TERMUX_SETUP_REPO "$HOME/termux-setup"


if ! [ "$?" == "0" ];
then
    echo "#!/bin/bash" >> "$HOME/download_termux-setup"
    
    echo "git clone $TERMUX_SETUP_REPO \$HOME/termux-setup" \
    >> "$HOME/download_termux-setup"

    echo "chmod -R +x \"\$HOME/termux-setup\"" \
    >> "$HOME/download_termux-setup"

    chmod +x "$HOME/download_termux-setup"
    
    echo "Something went wrong cloning the repo."
    echo "You can retry executing '~/download_termux-setup'."
else
    chmod -R +x "$HOME/termux-setup"
    "$HOME/termux-setup/find_extsd"
fi


echo ""
echo "Basic Termux setup done."
echo "You can now setup more things using the scripts contained in the"
echo "repository downloaded in ~/termux-setup' if you wish."
echo ""
echo "Restart Termux before continuing."
echo ""









