#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}


function usage
{

}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--h" ];
then
    usage
    abort
fi


if ! [ -d "$HOME/storage" ];
then
    echo "Execute 'termux-setup-storage' first, to grant Termux access"
    echo "to the Android filesystem."
    echo ""
    echo "It is also recommended, if you have not done it yet, to"
    echo "execute 'termux-change-repo' for selecting a mirror for"
    echo "downloading the packages, although is not strictly necesary."
    echo ""

    abort
fi




echo "=================================="
echo "Performing a basic Termux setup..."
echo "=================================="

if ! [ -f "$HOME/.bashrc" ];
then
    cp "$PREFIX/etc/bash.bashrc" "$HOME/.bashrc"
fi

if ! [ -f "$HOME/.environment" ];
then
    touch "$HOME/.environment"
    echo "source \$HOME/.environment" >> "$HOME/.bashrc"
fi


echo "Checking available packages..."
echo "------------------------------"

pkg update

echo ""


NEEDED_PACKAGES=""


if ! [ -f "$PREFIX/bin/git" ];
then
    NEEDED_PACKAGES+="git "
fi


if ! [ -f "$PREFIX/bin/sshd" ];
then
    NEEDED_PACKAGES+="openssh "
fi


if ! [ "$NEEDED_PACKAGES" == "" ];
then
    echo "Installing some packages..."
    echo "---------------------------"

    pkg install -y "$NEEDED_PACKAGES"
fi

echo ""


echo "$NEEDED_PACKAGES" | grep openssh

if [ "$?" == "0" ];
then
    echo "sshd" >> "$HOME/.bashrc"
    
    echo "Added sshd to startup."
    echo "Please, enter a password for login."
    echo ""

    passwd
fi
    

if ! [ -d "$HOME/storage/external-1" ];
then
    echo ""
    echo "No external SD card detected."
    echo "Skipping setting up extsd_id."
    echo ""

else
    if ! [ -f "$HOME/.extsd_id" ];
    then
        extsd_path=$(realpath "$HOME/storage/external-1")
        extsd_id=${extsd_path:9:9}

        echo $extsd_id > "$HOME/.extsd_id"
        echo "export EXT_SD=\"/storage/${extsd_id}\"" >> "$HOME/.environment"

        echo ""
        echo "Added .extsd_id file with the SD card ID."
        echo "Also, an EXT_SD variable has been added to .environment with its"
        echo "full path (more confortable that writing '/storage/external-1')."
        echo ""
    fi
fi


echo "Cloning 'termux-setup' repository..."
echo "------------------------------------"

git clone https://github.com/arithesage/termux-setup.git "$HOME/termux-setup"


echo ""
echo "Basic Termux setup done."
echo "You can now setup more things using the scripts contained in the"
echo "repository downloaded in ~/termux-setup' if you wish."
echo ""









