#!/bin/bash

function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo "$REASON"
    fi

    echo ""

    exit 1
}


if ! [ "$TERMUX_VERSION" == "" ] && [ "$ANDROID_DATA" == "" ];
then
    abort "This script must be executed in a Termux proot environment."
fi




ARCH=$(uname -m)

if ! [ "$ARCH" == "aarch64" ];
then
    abort "Box64 is intended for running x86_64 binaries in ARM64 platforms."
fi


if [ -f "/usr/local/bin/box64" ];
then
    abort "Box64 is already installed."
fi


if [ "$DISTRO_NAME" == "" ];
then
    DISTRO_NAME=$(cat /etc/os-release | grep ^ID= | cut -d '=' -f 2)

    if [ "$DISTRO_NAME" == "" ];
    then
        echo "Cannot detect distro name."
        abort "Set DISTRO_NAME environment variable manually."
    fi

    echo "Detected distro: ${DISTRO_NAME}"
    echo ""
fi


if ! [ "$ANDROID_DATA" == "" ];
then
    BOX86="box64-android"
else
    BOX86="box64-generic-arm"
fi


BOX64_URL="https://Pi-Apps-Coders.github.io/box64-debs/debian"


echo "==================="
echo "--- Box64 setup ---"
echo "==================="


if [ "$DISTRO_NAME" == "ubuntu" ];
then
    cp -f "$HOME/apt/fixed-ubuntu_sources.list" /etc/apt/sources.list
fi


if ! [ -f "/usr/bin/gpg" ];
then
    echo "Installing needed packages ..."
    echo "------------------------------"

    apt update    
    apt install -y dialog
    apt install -y gpg man python3 python-is-python3 wget

    echo ""
fi

if ! [ -d "/usr/share/keyrings" ];
then
    make -p "/usr/share/keyrings"
fi

if ! [ -f "/usr/share/keyrings/box64-archive-keyring.gpg" ];
then
    wget -qO- "https://pi-apps-coders.github.io/box64-debs/KEY.gpg" | \
    gpg --dearmor -o "/usr/share/keyrings/box64-archive-keyring.gpg"

    if ! [ "$?" == "0" ];
    then
        abort "Could not intall Box64 GPG key."
    fi

    echo "Added GPG key to keyrings."
fi


curl -s $BOX64_URL > /dev/null

if [ "$?" == "0" ];
then
    curl -s $BOX64_URL | grep "Moved" > /dev/null

    if [ "$?" == "0" ];
    then
        echo "It seems that the URL where the box64 packages are usually"
        echo "uploaded isn't available, so, we'll install a cached version."
        echo ""

        USE_CACHED_BOX64=1
    fi
fi


if ! [ "$USE_CACHED_BOX64" == "1" ];
then
    if ! [ -f "/etc/apt/sources/list.d/box64.sources" ];
    then
        echo "Types: deb" > /var/tmp/box64.sources

        echo "URIs: https://Pi-Apps-Coders.github.io/box64-debs/debian" \
        >> /var/tmp/box64.sources

        echo "Suites: ./" >> /var/tmp/box64.sources
        echo "Signed-By: /usr/share/keyrings/box64-archive-keyring.gpg" \
        >> /var/tmp/box64.sources

        mv /var/tmp/box64.sources /etc/apt/sources.list.d/

        echo "Added sources list for APT."
    fi
fi


dpkg --add-architecture amd64

echo "Enabled amd64 architecture in dpkg."

if [ "$DISTRO_NAME" == "ubuntu" ];
then
    cp "$HOME/apt/ubuntu-amd64.list" /etc/apt/sources.list.d/
fi


echo ""
echo "Updating APT sources..."
echo "-----------------------"

apt update


echo ""
echo "Installing ${BOX64} ..."
echo "----------------------------"

if ! [ "$USE_CACHED_BOX64"=="1" ];
then
    apt install -y ${BOX64}
else
    dpkg -i $(ls deb/box64*.deb)
fi

if ! [ "$?" == "0" ];
then
    echo ""
    abort "Failed installing box64."
fi


grep .local/bin "$HOME/.environment" > /dev/null

if ! [ "$?" == "0" ];
then
    echo "export PATH=\$PATH:\$HOME/scripts" >> "$HOME/.environment"
    echo "export PATH=\$PATH:\$HOME/.local/bin" >> "$HOME/.environment"

    grep .environment $HOME/.bashrc > /dev/null

    if ! [ "$?" == "0" ];
    then
        echo "source \$HOME/.environment" >> $HOME/.bashrc
    fi
fi

echo ""
echo "Finished!"
echo ""

