#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}




export BOX86_PROOT_DISTRO="debian-oldstable"
export BOX86_PROOT_NAME="box86-64"
export BOX86_PROOT_USER="puser"

PROOTS_PATH="$PREFIX/var/lib/proot-distro/installed-rootfs"
BOX86_PROOT_PATH="$PROOTS_PATH/$BOX86_PROOT_NAME"


if ! [ -f "$HOME/scripts/padmin" ];
then
    mkdir -p "$HOME/scripts"

    cp "$HOME/termux-setup/proot/padmin" "$HOME/scripts/"
    cp "$HOME/termux-setup/proot/penter" "$HOME/scripts/"
    cp "$HOME/termux-setup/proot/penter_admin" "$HOME/scripts/"
    cp "$HOME/termux-setup/proot/puser" "$HOME/scripts/"

    echo "export PATH=\$PATH:\$HOME/scripts" >> "$HOME/.environment"

    export PATH=$PATH:$HOME/scripts
fi


if ! [ -f "$HOME/.box86-proot_env" ];
then
    echo "source \$HOME/.box86-proot_env" >> "$HOME/.environment"

    echo "export BOX86_PROOT_DISTRO=\"${BOX86_PROOT_DISTRO}\"" >> \
         "$HOME/.box86-proot_env"

    echo "export BOX86_PROOT_NAME=\"${BOX86_PROOT_NAME}\"" >> \
         "$HOME/.box86-proot_env"

    echo "export BOX86_PROOT_USER=\"${BOX86_PROOT_USER}\"" >> \
         "$HOME/.box86-proot_env"

    echo "export BOX86_PROOT_PATH=\"${BOX86_PROOT_PATH}\"" >> \
         "$HOME/.box86-proot_env"    
fi


if ! [ -f "${PREFIX}/bin/proot-distro" ];
then
    echo "Installing proot-distro ..."
    echo "---------------------------"
    
    pkg update
    pkg install -y proot-distro

    if ! [ "$?" == "0" ];
    then
        abort "Failed."
    fi
fi


if ! [ -d "$BOX86_PROOT_PATH" ];
then
    echo ""
    echo "Installing ${BOX86_PROOT_NAME} ..."
    echo "-----------------------------------------"

    proot-distro install ${BOX86_PROOT_DISTRO} --override-alias $BOX86_PROOT_NAME

    if ! [ "$?" == "0" ];
    then
        abort "Failed."
    fi
fi


if ! [ -f "$BOX86_PROOT_PATH/usr/bin/gpg" ];
then
    echo ""
    echo "Installing some basic packages..."
    echo "---------------------------------"

    padmin $BOX86_PROOT_NAME apt update
    padmin $BOX86_PROOT_NAME apt upgrade -y
    padmin $BOX86_PROOT_NAME apt install -y dialog gpg man wget
fi


if ! [ -d "$BOX86_PROOT_PATH/home/${PROOT_USER}" ];
then
    echo ""
    echo "Creating a regular user without admin privileges..."
    echo "---------------------------------------------------"

    padmin $BOX86_PROOT_NAME useradd --create-home \
           --shell /bin/bash ${BOX86_PROOT_USER}
fi


echo ""
echo "Box86-64 proot environment ready."
echo ""
echo "The following scripts have been added to your PATH:"
echo ""
echo "- padmin: Executes a command line in the proot environment as root."
echo "          This is the recommended way to install software rather than"
echo "          using sudo. Only remember that this way your home dir is"
echo "          /root instead of /home/${BOX86_PROOT_USER}."
echo ""
echo "- puser: Executes a command line as a regular user."
echo "- penter: Enter the proot environment as ${BOX86_PROOT_USER}."
echo "- penter_admin: Enter the proot environment as root."
echo ""










