#!/bin/bash


function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo "$REASON"
    fi

    echo ""

    exit 1
}


function usage
{
    echo "Usage: penter_admin <proot name> [cmdline]"
    echo "       penter_admin <proot environment file> [cmdline]"
    echo ""
    echo "Enters into the given proot installation as root."
    echo "If a command line is provided, it is executed instead entering."
    echo ""
    echo "You can provide the proot name by parameters,"
    echo "the PROOT_NAME environment variable, or passing "
    echo "the environment file that 'setup_proot' generates in $HOME."
    echo ""
}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi




if [ -f "$1" ];
then
    grep -q "PROOT_NAME" "$1"

    if [ "$?" == "0" ];
    then
        source "$1"

        echo "Loaded proot $PROOT_NAME environment."
        echo ""
    fi

else
    PROOT_NAME=$1
fi

CMDLINE=$3

if [ "$PROOT_NAME" == "" ];
then
    echo "Can't login into a proot without knowing the PROOT_NAME."
    echo ""

    usage
    abort
fi


if [ "$EXT_SD" == "" ];
then
    if [ -f "$HOME/.extsd_id" ];
    then
        SD_BINDING="--bind /storage/$(cat $HOME/.extsd_id):/mnt/extsd"
    fi

else
    SD_BINDING="--bind $EXT_SD:/mnt/extsd"
fi


if ! [ "$PROOT_NAME" == "" ];
then
    if [ "$CMDLINE" == "" ];
    then
        echo "Entering into '$PROOT_NAME' proot as admin..."
    else
        echo "Executing '$CMDLINE' in '$PROOT_NAME' proot as admin..."
    fi

    if ! [ "$SD_BINDING" == "" ];
    then
        echo "(The external SD card will be mounted at /mnt/extsd)"
    fi

    echo "========================================================"
    echo ""
fi


if ! [ "$CMDLINE" == "" ];
then
    CMDLINE="-- $CMDLINE"
fi


proot-distro login $PROOT_NAME $SD_BINDING --shared-tmp $CMDLINE

