#!/bin/bash


function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo "$REASON"
    fi

    echo ""

    exit 1
}


function usage
{
    echo "Usage: penter_admin <proot name>"
    echo "       penter_admin <proot environment file>"
    echo ""
    echo "Enters into the given proot installation as root."
    echo "You can provide them in the options or pass the environment file that"
    echo "'setup_proot' generates in $HOME."
    echo ""
}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi




if [ -f "$1" ];
then
    grep -q "PROOT_NAME" "$1"

    if [ "$?" == "0" ];
    then
        source "$1"
    fi

else
    PROOT_NAME=$1
fi


if [ "$PROOT_NAME" == "" ]
then
    usage
    abort
fi


if ! [ "$EXT_SD" == "" ];
then
    SD_BINDING="--bind $EXT_SD:/mnt/extsd"
fi


proot-distro login $PROOT_NAME $SD_BINDING --shared-tmp

