#!/bin/bash


function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo "$REASON"
    fi

    echo ""

    exit 1
}


function usage
{
    echo "Usage: pexec_admin <proot name> <command line>"
    echo "       pexec_admin <proot environment file> <command line>"
    echo ""
    echo "Executes the given command line in the given proot installation."
    echo "The command line is executed as root."
    echo ""
    echo "You can provide them in the options or pass the environment file that"
    echo "'setup_proot' generates in $HOME."
    echo ""
}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi




if [ -f "$1" ];
then
    USING_ENV_FILE="1"

    grep -q "PROOT_NAME" "$1"

    if [ "$?" == "0" ];
    then
        source "$1"
    fi

else
    PROOT_NAME=$1
fi

if [ "$USING_ENV_FILE" == "1" ];
then
    CMDLINE=${@:1}
else
    CMDLINE=${@:2}
fi


if [ "$PROOT_NAME" == "" ] || [ "$CMDLINE" == "" ];
then
    usage
    abort
fi


if ! [ "$EXT_SD" == "" ];
then
    SD_BINDING="--bind $EXT_SD:/mnt/extsd"
fi


proot-distro login $PROOT_NAME $SD_BINDING --shared-tmp -- $CMDLINE

