#!/bin/bash


function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo "$REASON"
    fi

    echo ""

    exit 1
}


function usage
{
    echo "Usage: sshd_pid <proot name>"
    echo "Prints the PID of the given proot's SSH serve."
    echo ""
}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi




PROOT=$1


SSHD_PID=$(padmin ${PROOT} cat /var/run/sshd.pid)
