#!/bin/bash


function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo "$REASON"
    fi

    echo ""

    exit 1
}


function usage
{
    echo "Usage: stop_proot <proot name>"
    echo "'Turns off' the given proot."
    echo ""
}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi


if [ "$TERMUX_VERSION" == "" ];
then
    abort "This script is intended for Termux only."
fi




PROOT=$1

if [ "$PROOT" == "" ];
then
    usage
    abort
fi

echo "Trying to stop proot ..."

pexec_admin $PROOT stop_sshd

if ! [ "$?" == "0" ];
then
    abort "Command line returned non-zero. Something failed."
fi


#echo "Checking proot access ..."
#echo "-------------------------"

#check_proot $PROOT

#if [ "$?" == "1" ];
#then
#    abort "Failed!"
#fi


#PROOT_SSHD_PID_PATH="$PREFIX/var/lib/proot-distro/installed-rootfs"
#PROOT_SSHD_PID_PATH+="/${PROOT}/var/run/sshd.pid"


#if ! [ "$EXT_SD" == "" ];
#then
#    SD_BINDING="--bind $EXT_SD:/mnt/extsd"
#fi


#proot-distro login $PROOT $SD_BINDING \
#             --shared-tmp -- kill -9 $(cat /var/run/sshd.pid)

echo "Proot '${PROOT}' should be closed now."
echo ""


