#!/bin/bash

function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo "$REASON"
    fi

    echo ""

    exit 1
}


if ! [ "$TERMUX_VERSION" == "" ] && [ "$ANDROID_DATA" == "" ];
then
    abort "This script must be executed in a Termux proot environment."
fi




ARCH=$(uname -m)

if ! [[ $ARCH == armv* ]] && ! [ "$ARCH" == "aarch64" ];
then
    abort "Box86 is intended for running x86 binaries in ARM platforms."
fi


if [ -f "/usr/local/bin/box86" ];
then
    abort "Box86 is already installed."
fi


if [ "$DISTRO_NAME" == "" ];
then
    DISTRO_NAME=$(cat /etc/os-release | grep ^ID= | cut -d '=' -f 2)

    if [ "$DISTRO_NAME" == "" ];
    then
        echo "Cannot detect distro name."
        abort "Set DISTRO_NAME environment variable manually."
    fi

    echo "Detected distro: ${DISTRO_NAME}"
    echo ""
fi


if ! [ "$ANDROID_DATA" == "" ];
then
    BOX86="box86-android"
else
    BOX86="box86-generic-arm"
fi


BOX86_MAIN_URL="https://Pi-Apps-Coders.github.io/box86-debs/debian"
BOX86_MAIN_GPG_URL="https://pi-apps-coders.github.io/box86-debs/KEY.gpg"

BOX86_ALT_URL="https://ryanfortner.github.io/box86-debs"
BOX86_ALT_GPG_URL="https://ryanfortner.github.io/box86-debs/KEY.gpg"


echo "==================="
echo "--- Box86 setup ---"
echo "==================="


if [ "$DISTRO_NAME" == "ubuntu" ];
then
    cp -f "$HOME/apt/fixed-ubuntu_sources.list" /etc/apt/sources.list
fi


if ! [ -f "/usr/bin/gpg" ];
then
    echo "Installing needed packages ..."
    echo "------------------------------"

    apt update
    apt install -y dialog
    apt install -y gpg python3 python-is-python3 wget

    echo ""
fi


if ! [ -d "/usr/share/keyrings" ];
then
    make -p "/usr/share/keyrings"
fi


echo -n "Checking main box86 url..."
curl -s $BOX86_MAIN_URL > /dev/null

if [ "$?" == "0" ];
then
    BOX86_MAIN_URL_OK=1
    echo "OK"
else
    echo "ERROR"
fi


echo "Checking alt box86 url..."
curl -s $BOX86_ALT_URL > /dev/null

if [ "$?" == "0" ];
then
    BOX86_ALT_URL_OK=1
    echo "OK"
else
    echo "ERROR"
fi


if ! [ "$BOX86_MAIN_URL_OK" == "1" ] && ! [ "$BOX86_ALT_URL_OK" == "0"];
then
    echo "Failed connecting box86 repositories."
    echo "Using cached package."
    echo ""

    USE_CACHED_BOX86=1
fi


curl -s $BOX86_MAIN_URL | grep "Moved" > /dev/null

if [ "$?" == "0" ];
then
    echo "It seems main box86 repository is no longer there."
    echo "Checking alternative ..."

    curl -s $BOX86_ALT_URL | grep "Moved" > /dev/null

    if [ "$?" == "0" ];
    then
        echo "This one seems to be gone also."
        echo "Using cached package."

        USE_CACHED_BOX86=1
    else
        BOX86_URL=$BOX86_ALT_URL
        BOX86_GPG_URL=$BOX86_ALT_GPG_URL
    fi
else
    BOX86_URL=$BOX86_MAIN_URL
    BOX86_GPG_URL=$BOX86_MAIN_GPG_URL
fi


if ! [ -f "/usr/share/keyrings/box86.gpg" ];
then
    if ! [ "$USED_CACHED_BOX86" == "1"];
    then
        wget -qO- "$BOX86_GPG_URL" | \
        gpg --dearmor -o "/usr/share/keyrings/box86.gpg"
    else
        ls "$HOME/deb/*.gpg" | \
        gpg --dearmor -o "/usr/share/keyrings/box86.gpg"
    fi

    if ! [ "$?" == "0" ];
    then
        abort "Could not intall Box86 GPG key."
    fi

    echo "Added GPG key to keyrings."
fi


if ! [ "$USE_CACHED_BOX86" == "1" ];
then
    if ! [ -f "/etc/apt/sources/list.d/box86.sources" ];
    then
        echo "Types: deb" > /var/tmp/box86.sources

        echo "URIs: $BOX86_URL" \
        >> /var/tmp/box86.sources

        echo "Suites: ./" >> /var/tmp/box86.sources
        echo "Signed-By: /usr/share/keyrings/box86.gpg" \
        >> /var/tmp/box86.sources

        mv /var/tmp/box86.sources /etc/apt/sources.list.d/

        echo "Added sources list for APT."
    fi
fi


dpkg --add-architecture armhf
dpkg --add-architecture i386

echo "Enabled armhf and i386 architectures in dpkg."


if [ "$DISTRO_NAME" == "ubuntu" ];
then
    cp "$HOME/apt/ubuntu-i386.list" /etc/apt/sources.list.d/
fi


echo ""
echo "Updating APT sources..."
echo "-----------------------"

apt update


echo ""
echo "Installing libc6 and ${BOX86} ..."
echo "--------------------------------------"

apt install -y libc6:armhf

if ! [ "$?" == "0" ];
then
    echo ""
    abort "Failed installing libc6."
fi


if ! [ "$USE_CACHED_BOX86"=="1" ];
then
    apt install -y ${BOX86}
else
    dpkg -i $(ls deb/box86*.deb)
fi

if ! [ "$?" == "0" ];
then
    echo ""
    abort "Failed installing box86."
fi


grep .local/bin "$HOME/.environment" > /dev/null

if ! [ "$?" == "0" ];
then
    echo "export PATH=\$PATH:\$HOME/scripts" >> "$HOME/.environment"
    echo "export PATH=\$PATH:\$HOME/.local/bin" >> "$HOME/.environment"

    grep .environment $HOME/.bashrc > /dev/null

    if ! [ "$?" == "0" ];
    then
        echo "source \$HOME/.environment" >> $HOME/.bashrc
    fi
fi


echo ""
echo "Finished!"
echo ""

