#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}




if [ "$TERMUX_VERSION" == "" ];
then
    abort "This script is for Termux only."
fi


if [ "$BOX86_PROOT_DISTRO" == "" ];
then
    echo "BOX86_PROOT_DISTRO environment variable not detected."
    abort "Ensure the Box86-64 proot environment has been set-up and restart Termux."
fi


if [ -f "$BOX86_PROOT_PATH/usr/local/bin/box86" ];
then
    abort "Box86 already installed in proot environment."
fi


if ! [ -d "$BOX86_PROOT_PATH/root/scripts" ];
then
    mkdir "$BOX86_PROOT_PATH/root/scripts"
fi

cp "$HOME/termux-setup/box86-64/deb-manual-install" \
   "$BOX86_PROOT_PATH/root/scripts/"

cp "$HOME/termux-setup/box86-64/boxify" \
   "$BOX86_PROOT_PATH/usr/local/bin/boxify"

cp "$HOME/termux-setup/box86-64/box86-installer" \
   "$BOX86_PROOT_PATH/root/install-box86"
   
cp -r "$HOME/termux-setup/box86-64/apt" "$BOX86_PROOT_PATH/root/"
cp -r "$HOME/termux-setup/box86-64/deb" "$BOX86_PROOT_PATH/root/"

chmod +x "$BOX86_PROOT_PATH/usr/local/bin/boxify"
chmod +x "$BOX86_PROOT_PATH/root/install-box86"

bexec_admin /root/install-box86




