#!/bin/bash

if [ "$PROOT_DISTRO" == "" ];
then
    echo "The environment variable PROOT_DISTRO has not been set."
    echo "This script needs it to enter a proot distro."
    echo ""
    
    exit 1
fi

if ! [ "$EXT_SD" == "" ];
then
    SD_BINDING="--bind ${EXT_SD}:/mnt/extsd"
fi

if [ "$1" == "" ];
then
    echo "A command line to run in the proot environment would be nice..."
    echo ""
    exit 1
fi

proot-distro login ${PROOT_DISTRO} ${SD_BINDING} --shared-tmp -- $*

