#!/bin/bash

if [ "$PROOT_DISTRO" == "" ] || [ "$PROOT_USER" == "" ];
then
    echo "The environment variable PROOT_DISTRO, PROOT_USER,"
    echo "or both, have not been set."
    echo ""
    echo "This script needs both them to enter a proot distro."
    echo ""
    
    exit 1
fi

if ! [ "$EXT_SD" == "" ];
then
    SD_BINDING="--bind ${EXT_SD}:/mnt/extsd"
fi

if [ "$1" == "" ];
then
    echo "A command line to run in the proot environment would be nice..."
    echo ""
    exit 1
fi

proot-distro login ${PROOT_DISTRO} --user ${PROOT_USER} ${SD_BINDING} --shared-tmp -- $*

