#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}


function usage
{

}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--h" ];
then
    usage
    abort
fi



export PROOT_DISTRO="ubuntu-oldstable"
export PROOT_USER="puser"

PROOT_PATH="$PREFIX/var/lib/proot-distro/installed-rootfs/${PROOT_DISTRO}"


if ! [ -f "$HOME/scripts/padmin" ];
then
    mkdir -p "$HOME/scripts"

    cp "$HOME/termux-setup/proot-setup/padmin" "$HOME/scripts/"
    cp "$HOME/termux-setup/proot-setup/puser" "$HOME/scripts/"

    echo "export PATH=\$PATH:\$HOME/scripts" >> "$HOME/.environment"
    echo "source \$HOME/.proot_env" >> "$HOME/.environment"

    echo "export PROOT_DISTRO=\"${PROOT_DISTRO}\"" >> "$HOME/.proot_env"
    echo "export PROOT_USER=\"${PROOT_USER}\"" >> "$HOME/.proot_env"
    echo "export PROOT_PATH=\"${PROOT_PATH}\"" >> "$HOME/.proot_env"

    export PATH=$PATH:$HOME/scripts
fi


if ! [ -f "${PREFIX}/bin/proot-distro" ];
then
    echo "Installing proot-distro ..."
    echo "---------------------------"
    
    pkg update
    pkg install -y proot-distro

    if ! [ "$?" == "0" ];
    then
        abort "Failed."
    fi
fi


if ! [ -d "$PROOT_PATH" ];
then
    echo ""
    echo "Installing ${PROOT_DISTRO} ..."
    echo "------------------------------"

    proot-distro install ${PROOT_DISTRO}

    if ! [ "$?" == "0" ];
    then
        abort "Failed."
    fi
fi


if ! [ -f "$PROOT_DISTRO/usr/bin/gpg" ];
then
    echo ""
    echo "Installing some basic packages..."
    echo "---------------------------------"

    padmin apt update
    padmin apt install -y dialog gpg man wget
fi


if ! [ -d "$PROOT_DISTRO/home/${PROOT_USER}" ];
then
    echo ""
    echo "Creating a regular user without admin privileges..."
    echo "---------------------------------------------------"

    padmin useradd --create-home --shell /bin/bash ${PROOT_USER}
fi


echo ""
echo "Proot environment ready. The following scripts have been added"
echo "to your PATH:"
echo ""
echo "- padmin: Executes a command line in the proot environment as root."
echo "          This is the recommended way to install software rather than"
echo "          using sudo. Only remember that this way your home dir is"
echo "          /root instead of /home/${PROOT_USER}."
echo ""
echo "- puser: Executes a command line as a regular user."
echo "- penter_admin: Enter the proot environment as root."
echo "- penter: Enter the proot environment as ${PROOT_USER}."
echo ""










