#!/bin/bash


function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo "$REASON"
    fi

    echo ""

    exit 1
}


function usage
{
    echo "Usage: penter <proot name>"
    echo "Enters into the given proot installation as root."
    echo ""
}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi




PROOT=$1


if ! [ "$EXT_SD" == "" ];
then
    SD_BINDING="--bind $EXT_SD:/mnt/extsd"
fi


proot-distro login $PROOT $SD_BINDING --shared-tmp

