#!/bin/bash


function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo "$REASON"
    fi

    echo ""

    exit 1
}


function usage
{
    echo "Usage: puser <proot name> <usename> <command line>"
    echo "Executes the given command line in the given proot installation."
    echo "The command line is executed as the given username."
    echo ""
}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi




PROOT=$1
PROOT_USER=$2
CMDLINE=${@:3}

if [ "$PROOT" == "" ] || [ "$PROOT_USER" == "" ] || [ "$CMDLINE" == "" ];
then
    usage
    abort
fi


if ! [ "$EXT_SD" == "" ];
then
    SD_BINDING="--bind $EXT_SD:/mnt/extsd"
fi


proot-distro login $PROOT --user $PROOT_USER $SD_BINDING --shared-tmp -- $CMDLINE

