#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}


function usage
{
    echo "Usage: boxify-wine <Wine path>"
    echo ""
    echo "Create an script for every Wine executable that calls"
    echo "Box86 or Box64, depending of the executable architecture."
    echo ""
}


if ! [ "$TERMUX_VERSION" == "" ] && [ "$ANDROID_DATA" == "" ];
then
    abort "This script must be executed in a Termux proot environment."
fi


if [ "$1" == "" ] || [ "$1" == "" ] || [ "$1" == "" ];
then
    usage
    abort
fi




WINE_PATH=$1


if ! [ -f "${WINE_PATH}/bin/wineboot" ];
then
    abort "Wine not detected '$WINE_PATH'."
fi


if [ -f "${WINE_PATH}/bin/wineboot-x86" ];
then
    abort "This Wine installation has been boxified already."
fi


echo "Boxifying every Wine executable (not scripts) ..."
echo "-------------------------------------------------"

while IFS= read -r filename;
do
    if [ -f "${WINE_PATH}/bin/${filename}" ];
    then
        boxify "${WINE_PATH}/bin/${filename}" \
               "${WINE_PATH}/bin/${filename}-x86"
    fi
done < $HOME/wine-binaries


echo ""
echo "Updating symlinks ..."
echo "---------------------" 

ln -sf "${WINE_PATH}/bin/winegcc" "${WINE_PATH}/bin/winecpp"
ln -sf "${WINE_PATH}/bin/winegcc" "${WINE_PATH}/bin/wineg++"


echo "Done. Execute switch-wine ${WINE_PATH} to use this installation."
echo ""


