#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}


function usage
{
    echo "Usage: download-wine <branch> <version> [architecture]"
    echo "Branch is one of these: stable, devel or staging"
    echo "Packages will be downloaded in /var/tmp/wine-pkgs"
    echo ""
}


if [ "$1" == "" ] || [ "$?" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi


WINE_BRANCH=$1
WINE_VERSION=$2
ARCH=$3


if ! [ "$WINE_BRANCH" == "stable" ] && ! [ "$WINE_BRANCH" == "devel" ] && \
   ! [ "$WINE_BRANCH" == "staging" ];
then
    abort "Wrong branch name: '$WINE_BRANCH'."
fi


if [ "$ARCH" == "" ];
then
    ARCH=$(uname -m)

    if [ "$ARCH" == "aarch64" ];
    then
        ARCH="arm64"

    elif [[ $ARCH == armv* ]];
    then
        ARCH="armhf"
    fi
fi


if [ "$DISTRO_CODENAME" == "" ];
then
    DISTRO_CODENAME=$(cat /etc/os-release | \
                      grep VERSION_CODENAME | cut -d '=' -f2)
fi


if [ "$DISTRO_CODENAME" == "" ];
then
    echo "Can't detect your distro codename."
    abort "Do 'cat /etc/os-release' and manually export it in DISTRO_CODENAME"
fi


WINE_BUILDS_URL="https://dl.winehq.org/wine-builds"
DEBIAN_BUILDS_URL="${WINE_BUILDS_URL}/debian/dists/${DISTRO_CODENAME}"

WINE_SOURCES_URL="$DEBIAN_BUILDS_URL/winehq-${DISTRO_CODENAME}.sources"
WINE_GPG_URL="$WINE_BUILDS_URL/winehq.key"

WINE_DOWNLOAD_DIR="/var/tmp/wine-pkgs"


echo -n "Checking if Wine site is available..."
curl -s https://dl.winehq.org > /dev/null

if [ "$?" == "0" ];
then
    WINE_URL_OK=1
    echo "OK"
else
    echo "ERROR"
fi


if ! [ "$WINE_URL_OK" == "" ];
then
    abort "Can't download Wine."
fi


if ! [ -f "/etc/apt/keyrings/winehq-archive.key" ];
then
    if ! [ -d "/etc/apt/keyrings" ];
    then
        mkdir "/etc/apt/keyrings"
    fi

    wget -O /etc/apt/keyrings/winehq-archive.key $WINE_GPG_URL

    if ! [ "$?" == "0" ];
    then
        abort "Failed downloading Wine GPG key."
    fi

    echo "Added Wine GPG key to keyrings."
fi


echo ""
echo "Checking for updated APT sources.list..."
echo "----------------------------------------"
wget -NP /etc/apt/sources.list.d/ $WINE_SOURCES_URL

if [ "$?" == "0" ];
then
    echo "Updated sources.list in APT database."
fi


echo ""
echo "Updating APT database..."
echo "------------------------"

apt update


if ! [ -d "${WINE_DOWNLOAD_DIR}" ];
then
    mkdir -p "${WINE_DOWNLOAD_DIR}"
fi

cd $WINE_DOWNLOAD_DIR


echo ""
echo "Downloading wine-${WINE_BRANCH} (${WINE_VERSION})..."
echo "-----------------------------------------------------"

apt download wine-${WINE_BRANCH}:${ARCH}=${WINE_VERSION}~${DISTRO_CODENAME}-1
apt download wine-${WINE_BRANCH}-${ARCH}:${$WINE_VERSION}~${DISTRO_CODENAME}-1


if ! [ "$?" == "0" ];
then
    abort "Download failed."
fi

echo "Done."
echo ""









